# Numpy

Biblioteca que nos permite criar *arrays* multidimensionais

## Array Numpy


### Propiedades dos arrays

| Propriedade | Retorna  | Descrição |
| :-- | :-- | :-- |
| ndim | int |  número de dimensões (axes) |
| shape |  tupla |  quantidade de dados em cada dimensão |
| size | int | número de elementos |
| dtype| dtype | tipo das variáveis dos elementos |


In [22]:
import numpy as np

a_1 = np.array([1,1,1,])

print(a_1)
print(a_1.shape)
print(a_1.ndim)


[1 1 1]
(3,)
1
[[1 1 1]]
(1, 3)
3


In [27]:
a_2 = np.array([[1,1,1]])
print(a_2)
print(a_2.shape)
print(a_2.size)
print(a_3.ndim)


[[1 1 1]]
(1, 3)
3
2


In [26]:
a_3 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(a_3)
print(a_3.shape)
print(a_3.size)
print(a_3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [28]:
a_4 = np.arange(27).reshape(3,3,3)
a_4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])