# Exemplos de funcionalidades matemáticas no numpy

| Comando | Tipo |Descrição |
|:-|:-|:-|
| sin, cos, exp, sqr | Função | Seno, Cosseno, exponecial, raiz quadrada|
| pi, nan, inf | constantes | pi, similar a none, infinito |
| + - * / | operadores | operações aritiméticas |


No numpy, os arrays só aceitam um tipo de elemento.

***Obs!!!*** Eis aí, uma diferença entre arrays numpy e listas python

***ATENÇÃO!!!*** Se atentar as regras matemáticas de algebra linear em relação as liberdades de manipulação python/numpy

Ex: 

[1, 1, 1] todos elementos são do tipo inteiro int

[1.0, 1.1, 1.2] todos os elementos  são do tipo float

['a', 'b', 'c'] todos os elementos do são do tipo string



In [6]:
import numpy as np

a = np.sin((np.pi/2))
a

1.0

In [12]:
x = np.array([1, 2, 3, 4])

y = np.array([4, 3, 2, 1])

print(x)
print(y)
print(x + y)
print()



[1 2 3 4]
[4 3 2 1]
[5 5 5 5]
