# Método copy

Ao usarmos um sinal de igual não copiamos um array. O array é um objeto e possui um método para ser copiado

|Método|Descrição|
|:---:|:---:|
|.copy()| faz a cópia(deep copy) do array. OBS!! O sinal de igual não executa essa função|

Nota - a propiedade __*base*__ retorna o array utilizado para criar o array em questão

In [3]:
import numpy as np
a = np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
a[0] = 9
a

array([9, 1, 2, 3, 4, 5, 6, 7])

In [8]:
b 

array([9, 1, 2, 3, 4, 5, 6, 7])

In [9]:
a is b

True

In [10]:
b == a

array([ True,  True,  True,  True,  True,  True,  True,  True])

## Para copiarmos um array utilizamos o método copy

In [11]:
c = a.copy()
c 

array([9, 1, 2, 3, 4, 5, 6, 7])

In [14]:
a[0] = 1
print(a)
print(b)
print(c)

[1 1 2 3 4 5 6 7]
[1 1 2 3 4 5 6 7]
[9 1 2 3 4 5 6 7]


### Arrays podem compatilhar as mesmas propiedades, mesmo sendo arrays diferentes

In [16]:
d = a.reshape(2,4)
d

array([[1, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
print(d is a)
print(d.base is a)
print(a.base)

False
True
None
