# Índices e fatias de arrays

## indexing e slicing

|Sintaxe|Descrição|
|:-|:-|
|[i]| para 1 dimensão funciona como nas listas|
|[:i]| exibe um array que vai do indice 0 até o anterior ao i|
|[i:]| exibe um array que vai do indice posterior ao i até o último indice|
|[::i]| exibe todos os elementos variando de i em i|
|[::-i]| exibea sequência de elementos de trás pra frente variando de i em i|
|[a:b:c]|início, fim, step|

Para arrays multidimensionais:

|Sintaxe|Descrição|
|:-|:-|
|[i:j]| para exibir um elemento de uma matriz|
|[i,a:b]| retorna uma fatia da linha i com elementos das colunas de a até b
|[n,i,j]| outra dimensão, linha, coluna


In [2]:
import numpy as np

a = np.arange(10)**2
a
a[-1]

81

In [2]:
a[1]

1

In [5]:
a[:2]

array([0, 1], dtype=int32)

In [6]:
a[2:]

array([ 4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
a[::2]

array([ 0,  4, 16, 36, 64], dtype=int32)

In [9]:
a[2::]

array([ 4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [10]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [12]:
a[2:8:2]

array([ 4, 16, 36], dtype=int32)

## Para Arrays multidimensionais

In [14]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Podemos criar um "sub array" de b

In [16]:
b[0]

array([0, 1, 2, 3, 4])

In [15]:
b[1,1]

6

In [17]:
b[1,2:]

array([7, 8, 9])

In [18]:
b[2:,3:]

array([[13, 14],
       [18, 19]])

In [24]:
c  = np.arange(40).reshape(2,4,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [ ]:
c[1,1,1]