<h1> Operações com vetores e matrizes no Numpy

|Funções|Descrição|
|:-|:-|
|dot(a,b) ou @| retorna o produto escalar entre os vetores a e b|
|cross(a,b)| retorna o produto vetorial entre os vetores a e b|
|inner(a,b) e outer(a,b)|retorna o produto interno e externo entre os vetores a e b
|linag.norma(a)| retorna a norma do vetor a|
|matmul(a,b) ou @| produto entre as matrizes a e b
|linalg.det(A)| retorna o determinante de matriz A
|linalg.inv(A)| retorna a matriz inversa  de A


# Vetores

In [8]:
import numpy as np
import sympy as sp

In [5]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.ndim)

(3,)
1


# Produto escalar entre vetores

In [7]:
np.dot(a,a)

14

a_s = sp.Matrix([1,2,3])
print(a_s.T*a_s) # a transporta vezes o vetor retorna um escalar
a_s*a_s.T # o vetor vezes a transposta retorna uma matrix nxn



# Produto vetorial entre dois vetores

O produto vetorial entre dois vetores retorna, em termos geométricos, o vetor ortogonal a esses dois vetores

In [22]:
np.cross(a,a)

array([0, 0, 0])

In [23]:
v_1 =np.array([1,0,0])
v_2 =np.array([0,1,0])
np.cross(v_1,v_2)


array([0, 0, 1])

# Inner e outer

In [13]:
np.inner(a,a)


14

In [14]:
np.outer(a,a)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

# ATENÇÃO !!!

O numpy é uma biblioteca com foco na manipulação de dados e não nos conceitos teoricos mátematicos por tras da algebra linear.

Ao realizarmos a multiplicação a*a não obtemos uma multiplicação matricial


In [19]:
a

array([1, 2, 3])

In [18]:
a*a

array([1, 4, 9])

# Norma de um vetor

Conceito geométrico, podendo ser considerado com o "tamanho" ou "medida" de um vetor.


In [20]:
np.linalg.norm(a)

3.7416573867739413

In [21]:
np.sqrt(1**2+2**2+3**2)

3.7416573867739413

# Matrizes

### Utilizando o Numpy

In [24]:
A = np.array([[1,2],[4,4]])
A

array([[1, 2],
       [4, 4]])

In [25]:
np.matmul(A,A)

array([[ 9, 10],
       [20, 24]])

In [31]:
A@A

array([[ 9, 10],
       [20, 24]])

***Atenção!!!*** 
Se fizermo A*A no numpy,matematicamente o resultado será errado.

In [30]:
A*A

array([[ 1,  4],
       [16, 16]])

### Utilizando o sympy

In [28]:
A_s = sp.Matrix([[1,2],[4,4]])
A_s

Matrix([
[1, 2],
[4, 4]])

In [29]:
A_s*A_s

Matrix([
[ 9, 10],
[20, 24]])

## Cálculo de Determinante

In [32]:
np.linalg.det(A)

-4.0

No sympy

In [34]:
A_s.det()

-4

## Cálculo da inversa

In [36]:
np.linalg.inv(A)

array([[-1.  ,  0.5 ],
       [ 1.  , -0.25]])

No sympy

In [37]:
A_s**(-1)

Matrix([
[-1,  1/2],
[ 1, -1/4]])