# linalg

|Função(A)|Descrição|
|:-|:-|
|linalg.eig(A)| retorna os autovalores e autovetores de uma matrix A|
|linalg.solve(A,B)| resolve um sistema  do tipo AX=B|

### Auto Valores e Auto Vetores


In [23]:
import numpy as np

In [24]:
A = np.array([[5,3,-1],
             [3,4,0],
             [-1,0,2]])
A

array([[ 5,  3, -1],
       [ 3,  4,  0],
       [-1,  0,  2]])

In [27]:
l,v = np.linalg.eig(A)

In [28]:
l

array([7.64575131, 1.        , 2.35424869])

In [29]:
v

array([[-0.76505532, -0.57735027, -0.28523152],
       [-0.6295454 ,  0.57735027,  0.51994159],
       [ 0.13550992, -0.57735027,  0.8051731 ]])

# Solver para sistemas lineares

In [40]:
B = np.array([[1,1,1],[1,2,2],[2,1,3]])
B

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 3]])

In [41]:
C= np.array([6,9,11])
C

array([ 6,  9, 11])

In [42]:
np.linalg.solve(B,C)

array([3., 2., 1.])